site_name: Aviation
theme:
  name: material

nav:
  - Home: "index.md"
  - Aviation Model: "aviation.md"
  - API Documentation:
      - Aviation: api/index.md
      - Fleet: api/fleet.md

plugins:
  - mkdocstrings
  - search
  - bibtex:
      bib_file: "https://api.zotero.org/groups/5782724/collections/G847TDER/items?format=bibtex&limit=100"

markdown_extensions:
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
